apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-demo-chart.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "argo-demo-chart.name" . }}

