image:
  repository: nginx
  tag: 1.26

replicaCount: 1

service:
  nodePort: 30081
  type: NodePort

serviceAccount:
  create: true
  name: ""

httpRoute:
  enabled: false

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: argo-demo.local
      paths:
        - /
  tls: []

