apiVersion: v1
kind: Secret
metadata:
  name: argo-demo-repo
  namespace: argocd
  annotations:
    # Tell ArgoCD this is a git repository
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:niraj-243/argo-demo-app.git
  sshPrivateKeySecret: argo-ssh-key

